[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@uniswap/v4-core/=lib/v4-core/",
    "@uniswap/v3-core/=lib/v3-core/",
    "@uniswap/v2-core/=lib/v2-core/",
    "@uniswap/v4-periphery/=lib/v4-periphery/",
    "@uniswap/v3-periphery/=lib/v3-periphery/",
    "@uniswap/v2-periphery/=lib/v2-periphery/",
    "@uniswap/permit2/=lib/permit2/",
    "@uniswap/universal-router/=lib/universal-router/",
    "@openzeppelin/=lib/openzeppelin-contracts/"
]

[rpc_endpoints]
base = "${BASE_MAINNET_RPC}"
base_sepolia = "${BASE_SEPOLIA_RPC}"
arbitrum_sepolia = "${ARBITRUM_SEPOLIA_RPC}"
open_campus = "${OPEN_CAMPUS_RPC}"

[etherscan]
base = { key = "${ETHERSCAN_API_KEY}", url = "https://api.basescan.org/api" }
base_sepolia = { key = "${ETHERSCAN_API_KEY}", url = "https://api-sepolia.basescan.org/api" }
open_campus = { key = "${ETHERSCAN_API_KEY}", url = "https://opencampus-codex.blockscout.com/api" }